name: "Terraform Plan"

on:
  workflow_call:
    inputs:
      TF_VERSION:
        type: string
        required: true
# â‘  mainãƒ–ãƒ©ãƒ³ãƒã¸ã®ãƒ—ãƒ«ãƒªã‚¯ã‚¨ã‚¹ãƒˆãŒä½œæˆãƒ»æ›´æ–°ã•ã‚ŒãŸæ™‚ã«å®Ÿè¡Œ
  pull_request:
    branches:
      - main
    types: [opened, synchronize]


permissions:
  id-token: write      # AWS OIDCèªè¨¼ã«å¿…é ˆ
  contents: read       # ãƒªãƒã‚¸ãƒˆãƒªèª­ã¿å–ã‚Š
  pull-requests: write # PRã«ã‚³ãƒ¡ãƒ³ãƒˆã‚’æ›¸ãè¾¼ã‚€ãŸã‚ã«å¿…é ˆ

env:
  # ã‚ãªãŸã®ç’°å¢ƒã«åˆã‚ã›ã¦æ›¸ãæ›ãˆã¦ãã ã•ã„
  ROLE_TO_ASSUME: arn:aws:iam::662478938633:role/wpsite_role
  AWS_REGION: ap-northeast-1

jobs:
  terraform:
    name: "Terraform Plan Check"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - "." # Terraformã‚³ãƒ¼ãƒ‰ãŒãƒªãƒã‚¸ãƒˆãƒªç›´ä¸‹ã«ã‚ã‚‹å ´åˆã¯ "."
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # â‘¡ .terraform-version ã‹ã‚‰ãƒãƒ¼ã‚¸ãƒ§ãƒ³ã‚’å–å¾—
      - name: Get Terraform version
        id: terraform-version
        uses: bigwheel/get-terraform-version-action@v1.2.0
        with:
          path: "."
      # å–å¾—ã—ãŸãƒãƒ¼ã‚¸ãƒ§ãƒ³ã§ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.terraform-version.outputs.terraform-version }}

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Check if directory is not empty
        id: check
        run: |
          if [ "$(ls -A .)" ]; then
            echo "Directory is not empty"
          else
            echo "Directory is empty"
            exit 1
          fi

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        # planã«å¤±æ•—ã—ã¦ã‚‚å¾Œç¶šã®ã€Œã‚³ãƒ¡ãƒ³ãƒˆæŠ•ç¨¿ã€ã‚’å®Ÿè¡Œã™ã‚‹ãŸã‚ã« continue-on-error ã‚’ä½¿ç”¨
        run: terraform plan -no-color
        continue-on-error: true

      # Planã®çµæœãŒé•·ã™ãã‚‹å ´åˆã«å‚™ãˆã¦æ•´å½¢
      - name: Truncate terraform plan result
        run: |
          plan=$(cat <<'EOF'
          ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
          EOF
          )
          echo "PLAN<<EOF" >> $GITHUB_ENV
          echo "${plan}" | grep -v 'Refreshing state' | tail -c 65000 >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # â‘¢ PRã«çµæœã‚’ã‚³ãƒ¡ãƒ³ãƒˆã¨ã—ã¦æŠ•ç¨¿
      - name: Create comment from plan result
        uses: actions/github-script@v8 # ãƒãƒ¼ã‚¸ãƒ§ãƒ³ã‚’æœ€æ–°ã«æ›´æ–°
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Initialization âš™ï¸ã€€\`${{ steps.init.outcome }}\`
            #### Terraform Plan ğŸ“– \`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan Result</summary>

            \`\`\`terraform
            ${ process.env.PLAN }
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ matrix.directory }}\`, Workflow: \`${{ github.workflow }}\`*`;
            #*Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ matrix.directory }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })